// Objective-C API for talking to server Go package.
//   gobind -lang=objc server
//
// File is generated by gobind. Do not edit.

#ifndef __Server_H__
#define __Server_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void ServerAddTrackers(NSString* _Nullable trackers);

/**
 * Start brings up the embedded torrent server.

authToken is the per-launch secret that privileged HTTP endpoints require.
Callers that need to talk to those endpoints (the Flutter plugin) generate
one and pass it in. Passing "" mints an unguessable token that nobody holds,
which locks the privileged surface rather than opening it.
 */
FOUNDATION_EXPORT void ServerStart(NSString* _Nullable pathdb, NSString* _Nullable port, NSString* _Nullable authToken, BOOL roSets, BOOL searchWA);

FOUNDATION_EXPORT void ServerStop(void);

FOUNDATION_EXPORT NSString* _Nonnull ServerWaitServer(void);

#endif
